# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\2.3 信号与槽的使用\QtApp\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 600)
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox1.setGeometry(QtCore.QRect(130, 110, 421, 81))
        self.groupBox1.setObjectName("groupBox1")
        self.chkBoxUnder = QtWidgets.QCheckBox(self.groupBox1)
        self.chkBoxUnder.setEnabled(True)
        self.chkBoxUnder.setGeometry(QtCore.QRect(0, 40, 105, 22))
        self.chkBoxUnder.setTabletTracking(False)
        self.chkBoxUnder.setAcceptDrops(False)
        self.chkBoxUnder.setChecked(False)
        self.chkBoxUnder.setAutoRepeat(False)
        self.chkBoxUnder.setObjectName("chkBoxUnder")
        self.checkBoxBold = QtWidgets.QCheckBox(self.groupBox1)
        self.checkBoxBold.setGeometry(QtCore.QRect(140, 40, 105, 22))
        self.checkBoxBold.setChecked(True)
        self.checkBoxBold.setObjectName("checkBoxBold")
        self.chkBoxItalic = QtWidgets.QCheckBox(self.groupBox1)
        self.chkBoxItalic.setGeometry(QtCore.QRect(280, 40, 105, 22))
        self.chkBoxItalic.setChecked(False)
        self.chkBoxItalic.setObjectName("chkBoxItalic")
        self.groupBox2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox2.setGeometry(QtCore.QRect(130, 220, 421, 80))
        self.groupBox2.setObjectName("groupBox2")
        self.radioBlack = QtWidgets.QRadioButton(self.groupBox2)
        self.radioBlack.setGeometry(QtCore.QRect(0, 30, 132, 22))
        self.radioBlack.setChecked(True)
        self.radioBlack.setObjectName("radioBlack")
        self.radioRed = QtWidgets.QRadioButton(self.groupBox2)
        self.radioRed.setGeometry(QtCore.QRect(140, 30, 132, 22))
        self.radioRed.setObjectName("radioRed")
        self.radioBlue = QtWidgets.QRadioButton(self.groupBox2)
        self.radioBlue.setGeometry(QtCore.QRect(280, 30, 132, 22))
        self.radioBlue.setObjectName("radioBlue")
        self.textEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(130, 320, 421, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.textEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.textEdit.setFont(font)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textEdit.setReadOnly(False)
        self.textEdit.setBackgroundVisible(False)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 460, 421, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnClear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.btnClose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)

        self.retranslateUi(Dialog)
        self.btnOK.clicked.connect(Dialog.accept)
        self.btnClose.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox1.setTitle(_translate("Dialog", "GroupBox"))
        self.chkBoxUnder.setText(_translate("Dialog", "Underline"))
        self.checkBoxBold.setText(_translate("Dialog", "Bold"))
        self.chkBoxItalic.setText(_translate("Dialog", "Italic"))
        self.groupBox2.setTitle(_translate("Dialog", "GroupBox"))
        self.radioBlack.setText(_translate("Dialog", "Black"))
        self.radioRed.setText(_translate("Dialog", "Red"))
        self.radioBlue.setText(_translate("Dialog", "Blue"))
        self.textEdit.setPlainText(_translate("Dialog", "PyQt 编程\n"
"Python and Qt"))
        self.btnClear.setText(_translate("Dialog", "清空"))
        self.btnOK.setText(_translate("Dialog", "确定"))
        self.btnClose.setText(_translate("Dialog", "退出"))
