# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.8 QListWidget和QToolButton\QtApp\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 525)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 571, 461))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 191, 365))
        self.page.setObjectName("page")
        self.toolButton = QtWidgets.QToolButton(self.page)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 101, 24))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.page)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 20, 101, 24))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.page)
        self.toolButton_3.setGeometry(QtCore.QRect(0, 40, 101, 24))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.page)
        self.toolButton_4.setGeometry(QtCore.QRect(0, 60, 101, 24))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.page)
        self.toolButton_5.setGeometry(QtCore.QRect(0, 80, 101, 24))
        self.toolButton_5.setObjectName("toolButton_5")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Study\\3.8 QListWidget和QToolButton\\QtApp\\../../../彩图和配套源代码/chap03Widgets/Demo3_8ListWidget/QtApp/images/408.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon, "")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 191, 365))
        self.page_1.setObjectName("page_1")
        self.toolBox.addItem(self.page_1, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 191, 365))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, icon, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.listWidget = QtWidgets.QListWidget(self.tab_1)
        self.listWidget.setGeometry(QtCore.QRect(0, 140, 371, 291))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Study\\3.8 QListWidget和QToolButton\\QtApp\\../../../彩图和配套源代码/chap03Widgets/Demo3_8ListWidget/QtApp/images/724.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_2.addWidget(self.toolButton_6)
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/412.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon2)
        self.toolButton_7.setCheckable(False)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_2.addWidget(self.toolButton_7)
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_2.addWidget(self.toolButton_8)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_InitList = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("删除")
        self.action_InitList.setIcon(icon)
        self.action_InitList.setStatusTip("")
        self.action_InitList.setVisible(True)
        self.action_InitList.setObjectName("action_InitList")
        self.action_ClearList = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/images/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ClearList.setIcon(icon3)
        self.action_ClearList.setObjectName("action_ClearList")
        self.action_Insert = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Study\\3.8 QListWidget和QToolButton\\QtApp\\images/306.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Insert.setIcon(icon4)
        self.action_Insert.setObjectName("action_Insert")
        self.action_Add = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\Study\\3.8 QListWidget和QToolButton\\QtApp\\images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Add.setIcon(icon5)
        self.action_Add.setObjectName("action_Add")
        self.action_DeleteItem = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\Study\\3.8 QListWidget和QToolButton\\QtApp\\images/318.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DeleteItem.setIcon(icon6)
        self.action_DeleteItem.setObjectName("action_DeleteItem")
        self.action_All = QtWidgets.QAction(MainWindow)
        self.action_All.setObjectName("action_All")
        self.action_None = QtWidgets.QAction(MainWindow)
        self.action_None.setObjectName("action_None")
        self.action_Invs = QtWidgets.QAction(MainWindow)
        self.action_Invs.setObjectName("action_Invs")
        self.toolBar.addAction(self.action_InitList)
        self.toolBar.addAction(self.action_ClearList)
        self.toolBar.addAction(self.action_Insert)
        self.toolBar.addAction(self.action_Add)
        self.toolBar.addAction(self.action_DeleteItem)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "初始化列表"))
        self.toolButton_2.setText(_translate("MainWindow", "清除列表"))
        self.toolButton_3.setText(_translate("MainWindow", "插入项"))
        self.toolButton_4.setText(_translate("MainWindow", "删除项"))
        self.toolButton_5.setText(_translate("MainWindow", "添加项"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "QList"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), _translate("MainWindow", "Page1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page2"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item 1"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item 2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "当前项变化"))
        self.checkBox.setText(_translate("MainWindow", "可编辑"))
        self.toolButton_6.setText(_translate("MainWindow", "SelectItem"))
        self.toolButton_7.setText(_translate("MainWindow", "SelectAll"))
        self.toolButton_8.setText(_translate("MainWindow", "SelectNone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "QList_1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "QList_2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "QList_3"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_InitList.setText(_translate("MainWindow", "初始化列表"))
        self.action_InitList.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.action_ClearList.setText(_translate("MainWindow", "清除列表"))
        self.action_Insert.setText(_translate("MainWindow", "插入项"))
        self.action_Add.setText(_translate("MainWindow", "添加项"))
        self.action_DeleteItem.setText(_translate("MainWindow", "删除当前项"))
        self.action_All.setText(_translate("MainWindow", "全选"))
        self.action_All.setToolTip(_translate("MainWindow", "全选"))
        self.action_None.setText(_translate("MainWindow", "全不选"))
        self.action_Invs.setText(_translate("MainWindow", "反选"))
import icon_rc
