# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.4 日期时间数据\QtApp\widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1096, 341)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        Widget.setFont(font)
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(9, 0, 531, 331))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 20, 511, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_SetDate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_SetDate.setObjectName("pushButton_SetDate")
        self.gridLayout.addWidget(self.pushButton_SetDate, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_SetTime = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_SetTime.setObjectName("pushButton_SetTime")
        self.gridLayout.addWidget(self.pushButton_SetTime, 2, 2, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 1, 1, 1, 1)
        self.lineEdit_Time = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Time.setObjectName("lineEdit_Time")
        self.gridLayout.addWidget(self.lineEdit_Time, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 5, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 1, 1)
        self.pushButton_GetNowTime = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_GetNowTime.setObjectName("pushButton_GetNowTime")
        self.gridLayout.addWidget(self.pushButton_GetNowTime, 0, 1, 1, 1)
        self.lineEdit_Date = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Date.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Date.setObjectName("lineEdit_Date")
        self.gridLayout.addWidget(self.lineEdit_Date, 3, 2, 1, 1)
        self.lineEdit_DateTime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_DateTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DateTime.setObjectName("lineEdit_DateTime")
        self.gridLayout.addWidget(self.lineEdit_DateTime, 5, 2, 1, 1)
        self.label_DisplayStr = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_DisplayStr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DisplayStr.setObjectName("label_DisplayStr")
        self.gridLayout.addWidget(self.label_DisplayStr, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.pushButton_SetDateTime = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_SetDateTime.setObjectName("pushButton_SetDateTime")
        self.gridLayout.addWidget(self.pushButton_SetDateTime, 6, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 0, 541, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 30, 351, 241))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit_Search = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Search.setGeometry(QtCore.QRect(380, 160, 151, 25))
        self.lineEdit_Search.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(380, 120, 91, 31))
        self.label_5.setObjectName("label_5")
        self.pushButton_Close = QtWidgets.QPushButton(Widget)
        self.pushButton_Close.setGeometry(QtCore.QRect(940, 290, 112, 34))
        self.pushButton_Close.setObjectName("pushButton_Close")

        self.retranslateUi(Widget)
        self.pushButton_Close.clicked.connect(Widget.close)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.groupBox.setTitle(_translate("Widget", "日期时间"))
        self.pushButton_SetDate.setText(_translate("Widget", "设置日期"))
        self.label.setText(_translate("Widget", "时间"))
        self.pushButton_SetTime.setText(_translate("Widget", "设置时间"))
        self.lineEdit_Time.setInputMask(_translate("Widget", "99:99:99;0"))
        self.lineEdit_Time.setText(_translate("Widget", "::"))
        self.label_4.setText(_translate("Widget", "日期时间"))
        self.pushButton_GetNowTime.setText(_translate("Widget", "获取当前时间"))
        self.lineEdit_Date.setInputMask(_translate("Widget", "9999/99/99;0"))
        self.lineEdit_Date.setText(_translate("Widget", "//"))
        self.lineEdit_DateTime.setInputMask(_translate("Widget", "9999/99/99 99:99:99;0"))
        self.lineEdit_DateTime.setText(_translate("Widget", "// ::"))
        self.label_DisplayStr.setText(_translate("Widget", "字符串显示"))
        self.label_3.setText(_translate("Widget", "日期"))
        self.pushButton_SetDateTime.setText(_translate("Widget", "设置时间与日期"))
        self.groupBox_2.setTitle(_translate("Widget", "日历"))
        self.lineEdit_Search.setInputMask(_translate("Widget", "9999年99月99日;0"))
        self.lineEdit_Search.setText(_translate("Widget", "年月日"))
        self.label_5.setText(_translate("Widget", "查找日期："))
        self.pushButton_Close.setText(_translate("Widget", "关闭"))
