# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.7 QMainWindow和QAction\QtApp\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 0, 781, 501))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menuLanguage = QtWidgets.QMenu(self.menu_2)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/104.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon1)
        self.action_Save.setObjectName("action_Save")
        self.action_New = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/100.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon2)
        self.action_New.setObjectName("action_New")
        self.action_SaveAnother = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/106.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SaveAnother.setIcon(icon3)
        self.action_SaveAnother.setObjectName("action_SaveAnother")
        self.action_Close = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Close.setIcon(icon4)
        self.action_Close.setObjectName("action_Close")
        self.action_Copy = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/202.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Copy.setIcon(icon5)
        self.action_Copy.setObjectName("action_Copy")
        self.action_Paste = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/204.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Paste.setIcon(icon6)
        self.action_Paste.setObjectName("action_Paste")
        self.action_SlelctAll = QtWidgets.QAction(MainWindow)
        self.action_SlelctAll.setObjectName("action_SlelctAll")
        self.action_Clear = QtWidgets.QAction(MainWindow)
        self.action_Clear.setObjectName("action_Clear")
        self.action_Undo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/206.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Undo.setIcon(icon7)
        self.action_Undo.setObjectName("action_Undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        self.action_Redo.setCheckable(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/208.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Redo.setIcon(icon8)
        self.action_Redo.setObjectName("action_Redo")
        self.action_Bold = QtWidgets.QAction(MainWindow)
        self.action_Bold.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Bold.setIcon(icon9)
        self.action_Bold.setObjectName("action_Bold")
        self.action_Italic = QtWidgets.QAction(MainWindow)
        self.action_Italic.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/502.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Italic.setIcon(icon10)
        self.action_Italic.setObjectName("action_Italic")
        self.action_UnderLine = QtWidgets.QAction(MainWindow)
        self.action_UnderLine.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/504.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_UnderLine.setIcon(icon11)
        self.action_UnderLine.setObjectName("action_UnderLine")
        self.action_English = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/timg2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_English.setIcon(icon12)
        self.action_English.setObjectName("action_English")
        self.action_Chinese = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/CN.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Chinese.setIcon(icon13)
        self.action_Chinese.setObjectName("action_Chinese")
        self.action_Text = QtWidgets.QAction(MainWindow)
        self.action_Text.setCheckable(True)
        self.action_Text.setObjectName("action_Text")
        self.action_Cut = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(".\\Study\\3.7 QMainWindow和QAction\\QtApp\\images/200.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cut.setIcon(icon14)
        self.action_Cut.setObjectName("action_Cut")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_SaveAnother)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Close)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_SlelctAll)
        self.menu_Edit.addAction(self.action_Clear)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menuLanguage.addAction(self.action_English)
        self.menuLanguage.addAction(self.action_Chinese)
        self.menu_2.addAction(self.action_Bold)
        self.menu_2.addAction(self.action_Italic)
        self.menu_2.addAction(self.action_UnderLine)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menuLanguage.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_Text)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_SaveAnother)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Cut)
        self.toolBar.addAction(self.action_Copy)
        self.toolBar.addAction(self.action_Paste)
        self.toolBar.addAction(self.action_SlelctAll)
        self.toolBar.addAction(self.action_Clear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Undo)
        self.toolBar.addAction(self.action_Redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Bold)
        self.toolBar.addAction(self.action_Italic)
        self.toolBar.addAction(self.action_UnderLine)
        self.toolBar.addAction(self.action_English)
        self.toolBar.addAction(self.action_Chinese)

        self.retranslateUi(MainWindow)
        self.action_Copy.triggered.connect(self.plainTextEdit.copy)
        self.plainTextEdit.undoAvailable['bool'].connect(self.action_Undo.setEnabled)
        self.plainTextEdit.redoAvailable['bool'].connect(self.action_Redo.setEnabled)
        self.action_Cut.triggered.connect(self.plainTextEdit.cut)
        self.action_Paste.triggered.connect(self.plainTextEdit.paste)
        self.action_SlelctAll.triggered.connect(self.plainTextEdit.selectAll)
        self.action_Clear.triggered.connect(self.plainTextEdit.clear)
        self.action_Close.triggered.connect(MainWindow.close)
        self.action_Redo.triggered.connect(self.plainTextEdit.redo)
        self.action_Undo.triggered.connect(self.plainTextEdit.undo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Hello Wold!"))
        self.menu_File.setTitle(_translate("MainWindow", "文件"))
        self.menu_Edit.setTitle(_translate("MainWindow", "编辑"))
        self.menu_2.setTitle(_translate("MainWindow", "格式"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Open.setText(_translate("MainWindow", "打开"))
        self.action_Open.setToolTip(_translate("MainWindow", "打开文件"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Save.setText(_translate("MainWindow", "保存"))
        self.action_Save.setToolTip(_translate("MainWindow", "保存当前文件"))
        self.action_New.setText(_translate("MainWindow", "新建"))
        self.action_New.setToolTip(_translate("MainWindow", "新建文件"))
        self.action_SaveAnother.setText(_translate("MainWindow", "另存为"))
        self.action_SaveAnother.setToolTip(_translate("MainWindow", "另存为"))
        self.action_Close.setText(_translate("MainWindow", "关闭"))
        self.action_Close.setToolTip(_translate("MainWindow", "关闭程序"))
        self.action_Copy.setText(_translate("MainWindow", "复制"))
        self.action_Copy.setToolTip(_translate("MainWindow", "复制文本"))
        self.action_Copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_Paste.setText(_translate("MainWindow", "粘贴"))
        self.action_Paste.setToolTip(_translate("MainWindow", "粘贴文本"))
        self.action_Paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_SlelctAll.setText(_translate("MainWindow", "全选"))
        self.action_SlelctAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action_Clear.setText(_translate("MainWindow", "清除"))
        self.action_Clear.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_Undo.setText(_translate("MainWindow", "撤销"))
        self.action_Undo.setToolTip(_translate("MainWindow", "撤销上次操作"))
        self.action_Redo.setText(_translate("MainWindow", "重做"))
        self.action_Redo.setToolTip(_translate("MainWindow", "重做上次操作"))
        self.action_Bold.setText(_translate("MainWindow", "粗体"))
        self.action_Bold.setToolTip(_translate("MainWindow", "字体加粗"))
        self.action_Italic.setText(_translate("MainWindow", "斜体"))
        self.action_Italic.setToolTip(_translate("MainWindow", "字体倾斜"))
        self.action_UnderLine.setText(_translate("MainWindow", "下划线"))
        self.action_English.setText(_translate("MainWindow", "English"))
        self.action_Chinese.setText(_translate("MainWindow", "中文"))
        self.action_Text.setText(_translate("MainWindow", "显示按钮文字"))
        self.action_Cut.setText(_translate("MainWindow", "剪切"))
        self.action_Cut.setToolTip(_translate("MainWindow", "剪切文本"))
        self.action_Cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
