# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\2.5 资源文件的使用\QtAPP\widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        Widget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/images/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Widget.setWindowIcon(icon)
        self.groupBoxAge = QtWidgets.QGroupBox(Widget)
        self.groupBoxAge.setGeometry(QtCore.QRect(70, 90, 661, 231))
        self.groupBoxAge.setObjectName("groupBoxAge")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBoxAge)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 621, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_SetAge = QtWidgets.QSlider(self.gridLayoutWidget)
        self.slider_SetAge.setMaximum(100)
        self.slider_SetAge.setOrientation(QtCore.Qt.Horizontal)
        self.slider_SetAge.setObjectName("slider_SetAge")
        self.gridLayout.addWidget(self.slider_SetAge, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_ageInt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ageInt.setObjectName("lineEdit_ageInt")
        self.gridLayout.addWidget(self.lineEdit_ageInt, 1, 1, 1, 2)
        self.lineEdit_ageStr = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ageStr.setObjectName("lineEdit_ageStr")
        self.gridLayout.addWidget(self.lineEdit_ageStr, 2, 1, 1, 2)
        self.groupBoxName = QtWidgets.QGroupBox(Widget)
        self.groupBoxName.setGeometry(QtCore.QRect(70, 330, 661, 151))
        self.groupBoxName.setObjectName("groupBoxName")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxName)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 621, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_inputName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_inputName.setObjectName("lineEdit_inputName")
        self.gridLayout_2.addWidget(self.lineEdit_inputName, 1, 1, 1, 1)
        self.lineEdit_nameStr = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_nameStr.setObjectName("lineEdit_nameStr")
        self.gridLayout_2.addWidget(self.lineEdit_nameStr, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 2, 1, 1)
        self.groupBoxButton = QtWidgets.QGroupBox(Widget)
        self.groupBoxButton.setGeometry(QtCore.QRect(70, 470, 661, 91))
        self.groupBoxButton.setTitle("")
        self.groupBoxButton.setObjectName("groupBoxButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBoxButton)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 621, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_OK = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout.addWidget(self.pushButton_OK)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Cancel.setIcon(icon1)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)

        self.retranslateUi(Widget)
        self.pushButton_Cancel.clicked.connect(Widget.close)
        self.pushButton_OK.clicked.connect(Widget.close)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.groupBoxAge.setTitle(_translate("Widget", "年龄设置"))
        self.label_3.setText(_translate("Widget", "ageChanged(int)响应"))
        self.label_2.setText(_translate("Widget", "ageChanged(str)响应"))
        self.label.setText(_translate("Widget", "设置年龄（0-100）"))
        self.groupBoxName.setTitle(_translate("Widget", "姓名设置"))
        self.label_5.setText(_translate("Widget", "nameChanged(str)响应"))
        self.label_4.setText(_translate("Widget", "输入姓名"))
        self.pushButton.setText(_translate("Widget", "设置姓名"))
        self.pushButton_OK.setText(_translate("Widget", "OK"))
        self.pushButton_Cancel.setText(_translate("Widget", "Cancel"))
import res_rc
