# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.1 数据输入输出\Widgets\widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(807, 600)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        Widget.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 19, 761, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_LineEdit = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_LineEdit.setObjectName("groupBox_LineEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_LineEdit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 721, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.lineEdit_Price = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Price.setObjectName("lineEdit_Price")
        self.gridLayout.addWidget(self.lineEdit_Price, 0, 4, 1, 1)
        self.lineEdit_Total_Line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Total_Line.setObjectName("lineEdit_Total_Line")
        self.gridLayout.addWidget(self.lineEdit_Total_Line, 1, 4, 1, 1)
        self.lineEdit_Count = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Count.setObjectName("lineEdit_Count")
        self.gridLayout.addWidget(self.lineEdit_Count, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.pushButton_Total = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Total.setObjectName("pushButton_Total")
        self.gridLayout.addWidget(self.pushButton_Total, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_LineEdit)
        self.groupBox_SpinBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_SpinBox.setObjectName("groupBox_SpinBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_SpinBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 721, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(36)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox.setMaximum(1000)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 1, 1, 1)
        self.lineEdit_Total_Spin = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Total_Spin.setObjectName("lineEdit_Total_Spin")
        self.gridLayout_2.addWidget(self.lineEdit_Total_Spin, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_SpinBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 520, 761, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_Close = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.horizontalLayout_2.addWidget(self.pushButton_Close)

        self.retranslateUi(Widget)
        self.pushButton_Close.clicked.connect(Widget.close)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.groupBox_LineEdit.setTitle(_translate("Widget", "Line Edit输入与输出"))
        self.label.setText(_translate("Widget", "数量"))
        self.label_2.setText(_translate("Widget", "单价"))
        self.label_3.setText(_translate("Widget", "总价"))
        self.pushButton_Total.setText(_translate("Widget", "计算总价"))
        self.groupBox_SpinBox.setTitle(_translate("Widget", "Spin Box输入与输出"))
        self.label_5.setText(_translate("Widget", " 单价   "))
        self.label_6.setText(_translate("Widget", "总价"))
        self.label_4.setText(_translate("Widget", "     重量      "))
        self.pushButton_Close.setText(_translate("Widget", "Close"))
