# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.10 QTableWidget\QtApp\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 533)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setToolTipDuration(-1)
        self.splitter_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter_2.setLineWidth(1)
        self.splitter_2.setMidLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(5)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_autoRowHeight = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_autoRowHeight.setObjectName("pushButton_autoRowHeight")
        self.gridLayout.addWidget(self.pushButton_autoRowHeight, 5, 0, 1, 1)
        self.pushButton_setRowNum = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_setRowNum.setObjectName("pushButton_setRowNum")
        self.gridLayout.addWidget(self.pushButton_setRowNum, 1, 0, 1, 1)
        self.pushButton_deleteRow = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_deleteRow.setObjectName("pushButton_deleteRow")
        self.gridLayout.addWidget(self.pushButton_deleteRow, 4, 0, 1, 1)
        self.radioButton_row = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_row.setObjectName("radioButton_row")
        self.gridLayout.addWidget(self.radioButton_row, 9, 0, 1, 1)
        self.pushButton_addRow = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_addRow.setObjectName("pushButton_addRow")
        self.gridLayout.addWidget(self.pushButton_addRow, 3, 1, 1, 1)
        self.radioButton_col = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_col.setChecked(True)
        self.radioButton_col.setObjectName("radioButton_col")
        self.gridLayout.addWidget(self.radioButton_col, 9, 1, 1, 1)
        self.pushButton_insertRow = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_insertRow.setObjectName("pushButton_insertRow")
        self.gridLayout.addWidget(self.pushButton_insertRow, 3, 0, 1, 1)
        self.pushButton_setTableHead = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_setTableHead.setObjectName("pushButton_setTableHead")
        self.gridLayout.addWidget(self.pushButton_setTableHead, 0, 0, 1, 2)
        self.checkBox_setColor = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_setColor.setChecked(True)
        self.checkBox_setColor.setObjectName("checkBox_setColor")
        self.gridLayout.addWidget(self.checkBox_setColor, 7, 1, 1, 1)
        self.checkBox_setColHead = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_setColHead.setChecked(True)
        self.checkBox_setColHead.setObjectName("checkBox_setColHead")
        self.gridLayout.addWidget(self.checkBox_setColHead, 8, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.pushButton_readTable = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_readTable.setObjectName("pushButton_readTable")
        self.gridLayout.addWidget(self.pushButton_readTable, 6, 0, 1, 2)
        self.pushButton_initTableData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_initTableData.setObjectName("pushButton_initTableData")
        self.gridLayout.addWidget(self.pushButton_initTableData, 2, 0, 1, 2)
        self.pushButton_clearTableConten = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clearTableConten.setObjectName("pushButton_clearTableConten")
        self.gridLayout.addWidget(self.pushButton_clearTableConten, 4, 1, 1, 1)
        self.checkBox_editabled = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_editabled.setChecked(True)
        self.checkBox_editabled.setObjectName("checkBox_editabled")
        self.gridLayout.addWidget(self.checkBox_editabled, 7, 0, 1, 1)
        self.checkBox_diaplayRowHead = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_diaplayRowHead.setChecked(True)
        self.checkBox_diaplayRowHead.setObjectName("checkBox_diaplayRowHead")
        self.gridLayout.addWidget(self.checkBox_diaplayRowHead, 8, 0, 1, 1)
        self.pushButton_autoColWidth = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_autoColWidth.setObjectName("pushButton_autoColWidth")
        self.gridLayout.addWidget(self.pushButton_autoColWidth, 5, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/images/boy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/images/girl.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.splitter)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_autoRowHeight.setText(_translate("MainWindow", "自动调节行高"))
        self.pushButton_setRowNum.setText(_translate("MainWindow", "设置行数"))
        self.pushButton_deleteRow.setText(_translate("MainWindow", "删除当前行"))
        self.radioButton_row.setText(_translate("MainWindow", "行选择"))
        self.pushButton_addRow.setText(_translate("MainWindow", "添加行"))
        self.radioButton_col.setText(_translate("MainWindow", "单元格选择"))
        self.pushButton_insertRow.setText(_translate("MainWindow", "插入行"))
        self.pushButton_setTableHead.setText(_translate("MainWindow", "设置表头"))
        self.checkBox_setColor.setText(_translate("MainWindow", "间隔行底色"))
        self.checkBox_setColHead.setText(_translate("MainWindow", "显示列表头"))
        self.pushButton_readTable.setText(_translate("MainWindow", "读取表格内容到列表"))
        self.pushButton_initTableData.setText(_translate("MainWindow", "初始化表格数据"))
        self.pushButton_clearTableConten.setText(_translate("MainWindow", "清除表格内容"))
        self.checkBox_editabled.setText(_translate("MainWindow", "表格可编辑"))
        self.checkBox_diaplayRowHead.setText(_translate("MainWindow", "显示行表头"))
        self.pushButton_autoColWidth.setText(_translate("MainWindow", "自动调节列宽"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "列1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "列2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "列3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "列4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "列5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "列6"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "（1，1）"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "（1，2）"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "（2，1）"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "（2，2）"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "（3，1）"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "（4，1）"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "（5，1）"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
import images_rc
