# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.2 QPushButton\QtApp\widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(515, 368)
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 481, 71))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 461, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Bold = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Bold.setCheckable(True)
        self.pushButton_Bold.setAutoExclusive(True)
        self.pushButton_Bold.setObjectName("pushButton_Bold")
        self.horizontalLayout_2.addWidget(self.pushButton_Bold)
        self.pushButton_Italic = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Italic.setCheckable(True)
        self.pushButton_Italic.setAutoExclusive(True)
        self.pushButton_Italic.setObjectName("pushButton_Italic")
        self.horizontalLayout_2.addWidget(self.pushButton_Italic)
        self.pushButton_Underline = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Underline.setCheckable(True)
        self.pushButton_Underline.setAutoExclusive(True)
        self.pushButton_Underline.setObjectName("pushButton_Underline")
        self.horizontalLayout_2.addWidget(self.pushButton_Underline)
        self.groupBox_3 = QtWidgets.QGroupBox(Widget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 160, 481, 51))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 461, 24))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ReadOnly = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_ReadOnly.setObjectName("checkBox_ReadOnly")
        self.horizontalLayout_3.addWidget(self.checkBox_ReadOnly)
        self.checkBox_EnaBled = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_EnaBled.setObjectName("checkBox_EnaBled")
        self.horizontalLayout_3.addWidget(self.checkBox_EnaBled)
        self.checkBox_ClearButtonEnabled = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_ClearButtonEnabled.setObjectName("checkBox_ClearButtonEnabled")
        self.horizontalLayout_3.addWidget(self.checkBox_ClearButtonEnabled)
        self.lineEdit = QtWidgets.QLineEdit(Widget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 224, 481, 101))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_Close = QtWidgets.QPushButton(Widget)
        self.pushButton_Close.setGeometry(QtCore.QRect(381, 330, 111, 31))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Left = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Left.setCheckable(True)
        self.pushButton_Left.setChecked(False)
        self.pushButton_Left.setAutoExclusive(True)
        self.pushButton_Left.setAutoDefault(False)
        self.pushButton_Left.setFlat(True)
        self.pushButton_Left.setObjectName("pushButton_Left")
        self.horizontalLayout.addWidget(self.pushButton_Left)
        self.pushButton_Center = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Center.setCheckable(True)
        self.pushButton_Center.setAutoExclusive(True)
        self.pushButton_Center.setFlat(True)
        self.pushButton_Center.setObjectName("pushButton_Center")
        self.horizontalLayout.addWidget(self.pushButton_Center)
        self.pushButton_Right = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Right.setCheckable(True)
        self.pushButton_Right.setAutoExclusive(True)
        self.pushButton_Right.setAutoDefault(False)
        self.pushButton_Right.setFlat(True)
        self.pushButton_Right.setObjectName("pushButton_Right")
        self.horizontalLayout.addWidget(self.pushButton_Right)

        self.retranslateUi(Widget)
        self.pushButton_Close.clicked.connect(Widget.close)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton_Bold.setText(_translate("Widget", "加粗"))
        self.pushButton_Italic.setText(_translate("Widget", "倾斜"))
        self.pushButton_Underline.setText(_translate("Widget", "下划线"))
        self.checkBox_ReadOnly.setText(_translate("Widget", "ReadOnly"))
        self.checkBox_EnaBled.setText(_translate("Widget", "Enabled"))
        self.checkBox_ClearButtonEnabled.setText(_translate("Widget", "ClearButtonEnabled"))
        self.pushButton_Close.setText(_translate("Widget", "关闭"))
        self.pushButton_Left.setText(_translate("Widget", "居左"))
        self.pushButton_Center.setText(_translate("Widget", "居中"))
        self.pushButton_Right.setText(_translate("Widget", "居右"))
