# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Study\3.9 QTree Widget和QDock Widget\QtApp\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 601, 481))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 10, 591, 411))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.toolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents_3)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/31.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_2.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon1)
        self.verticalLayout.addWidget(self.treeWidget)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menuBar.setObjectName("menuBar")
        self.menu_1 = QtWidgets.QMenu(self.menuBar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_OpenFolder = QtWidgets.QAction(MainWindow)
        self.action_OpenFolder.setIcon(icon)
        self.action_OpenFolder.setObjectName("action_OpenFolder")
        self.action_OpenFile = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/Documents.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OpenFile.setIcon(icon2)
        self.action_OpenFile.setObjectName("action_OpenFile")
        self.action_Delete = QtWidgets.QAction(MainWindow)
        self.action_Delete.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete.setIcon(icon3)
        self.action_Delete.setObjectName("action_Delete")
        self.action_Ergodic = QtWidgets.QAction(MainWindow)
        self.action_Ergodic.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/export1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Ergodic.setIcon(icon4)
        self.action_Ergodic.setObjectName("action_Ergodic")
        self.action_Enlarge = QtWidgets.QAction(MainWindow)
        self.action_Enlarge.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Enlarge.setIcon(icon5)
        self.action_Enlarge.setObjectName("action_Enlarge")
        self.action_Narrow = QtWidgets.QAction(MainWindow)
        self.action_Narrow.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Narrow.setIcon(icon6)
        self.action_Narrow.setObjectName("action_Narrow")
        self.action_Actual = QtWidgets.QAction(MainWindow)
        self.action_Actual.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Actual.setIcon(icon7)
        self.action_Actual.setObjectName("action_Actual")
        self.action_SuitableWidth = QtWidgets.QAction(MainWindow)
        self.action_SuitableWidth.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/15.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SuitableWidth.setIcon(icon8)
        self.action_SuitableWidth.setObjectName("action_SuitableWidth")
        self.action_SuitableHeight = QtWidgets.QAction(MainWindow)
        self.action_SuitableHeight.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/426.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SuitableHeight.setIcon(icon9)
        self.action_SuitableHeight.setObjectName("action_SuitableHeight")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon10)
        self.action_Exit.setObjectName("action_Exit")
        self.toolBar.addAction(self.action_OpenFolder)
        self.toolBar.addAction(self.action_OpenFile)
        self.toolBar.addAction(self.action_Delete)
        self.toolBar.addAction(self.action_Ergodic)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Enlarge)
        self.toolBar.addAction(self.action_Narrow)
        self.toolBar.addAction(self.action_Actual)
        self.toolBar.addAction(self.action_SuitableWidth)
        self.toolBar.addAction(self.action_SuitableHeight)
        self.menu_1.addAction(self.action_OpenFolder)
        self.menu_1.addAction(self.action_OpenFile)
        self.menu_1.addAction(self.action_Delete)
        self.menu_1.addAction(self.action_Ergodic)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_Exit)
        self.menu_2.addAction(self.action_Enlarge)
        self.menu_2.addAction(self.action_Narrow)
        self.menu_2.addAction(self.action_Actual)
        self.menu_2.addAction(self.action_SuitableWidth)
        self.menu_2.addAction(self.action_SuitableHeight)
        self.menuBar.addAction(self.menu_1.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "待显示图片"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.dockWidget_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "文件目录树"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "节点"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "类型"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "图片"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "分组1"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "图片"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "分组2"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "图片"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.menu_1.setTitle(_translate("MainWindow", "目录树"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.action_OpenFolder.setText(_translate("MainWindow", "打开文件夹"))
        self.action_OpenFile.setText(_translate("MainWindow", "打开文件"))
        self.action_Delete.setText(_translate("MainWindow", "删除节点"))
        self.action_Ergodic.setText(_translate("MainWindow", "遍历节点"))
        self.action_Enlarge.setText(_translate("MainWindow", "放大"))
        self.action_Narrow.setText(_translate("MainWindow", "缩小"))
        self.action_Actual.setText(_translate("MainWindow", "实际大小"))
        self.action_SuitableWidth.setText(_translate("MainWindow", "适合宽度"))
        self.action_SuitableHeight.setText(_translate("MainWindow", "适合高度"))
        self.action_Exit.setText(_translate("MainWindow", "退出"))
import icons_rc
